### ISSUE TITLE
Why the api is needed in such project?

### ISSUE THREAD

**Issue by obscurefreeman** [j4ckofalltrades/steam-current-game#12]
I found that projects like this all need api such as [Steam Stat](https://github.com/Ananto30/steam-stat/).
Why the Steam api is needed when I depoly it on vercel? How does it work?

**Comment by j4ckofalltrades** [comment]
>  Why the Steam api is needed when I depoly it on vercel? How does it work?

The Steamworks Web API exposes data such as user profile and current game being played. The [Web API Overview](https://partner.steamgames.com/doc/webapi_overview) explains how this works and provides examples.

For a full list of everything offered by the API, check the [API Reference](https://partner.steamgames.com/doc/webapi).
